import time
divider = "-------------------------"
print("========== MATHSASSIST STARTED ==========")
time.sleep(1)
print("Welcome to MathsAssist")
print(divider)
time.sleep(1)
print("You're on Build 1 PRE-ALPHA")
print(divider)
time.sleep(3)
print("What would you like to do?")
print(divider)
print("Options:")
print("1 | Addition")
print("2 | Subtraction")
print("3 | Multiplication")
print ("4 | Division")
navigation = int(input("Enter a number: "))
if navigation == 1:
    time.sleep(1)
    additionnuma = int(input("Enter number A: "))
    time.sleep(1)
    print("========== NUMBER A SUBMITTED ==========")
    time.sleep(1)
    additionnumb = int(input("Enter number B: "))
    print("========== NUMBER B SUBMITTED ==========")
    addition = additionnuma + additionnumb
    time.sleep(1)
    print("Result is", addition)
    time.sleep(3)
quit()